ALTER TABLE `users`
ADD COLUMN `bio` TEXT DEFAULT NULL,
ADD COLUMN `avatar` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `social_linkedin` VARCHAR(255) DEFAULT NULL,
ADD COLUMN `social_instagram` VARCHAR(255) DEFAULT NULL;
